---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list: 
      - recipe[apt::default]
      - recipe[kibana::install]
    attributes:
      kibana:
        legacy_mode: false
